import { OSMLocation } from './location';

export interface VehiclePosition {
    _id?: string,
    V?: number,
    AccountId?: number,
    CoDriverActivity?: number,
    CreatedDate?: Date,
    DayLight?: boolean,
    DriverActivity?: number,
    DriverCardNumber?: string,
    DriverId?: number,
    DriverSiteId?: number,
    DTCOTimeStamp?: number,
    GPSTimeStamp?: number,
    HeadingChange?: number,
    Latitude?: number,
    Longitude?: number,
    SnapshotType?: number,
    TimeZone?: number,
    UpdatedDate?: Date,
    VehicleId?: number,
    VehicleSiteId?: number,
    VehicleSpeed?: number,
    VRN?: string,
    CoDriverId?: number,
    CoDriverCardNumber?: string,
    CoDriverSiteId?: number,
    GPSSpeed?: number,
    VehicleIsInMotion?: boolean,
    DriverCardIssuingMemberState?: string,
    CoDriverCardIssuingMemberState?: string,
    EngineSpeed?: number,
    OdometerReading?: number,
    UtilizedCapacity?: string,
    BatteryVoltage?: string,
    Flags?: number,
    OSMLocation?: OSMLocation
}