export default [
    {
        name: 'test vehicle',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now() - (1000 * 60 * (5 + Math.random() * 10)),
        remainingTime: 201500320,
        driver: undefined,
    },
    {
        name: 'test vehicle_1',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now() - (1000 * 60 * (5 + Math.random() * 10)),
        remainingTime: 201500320,
        driver: undefined,
    },
    {
        name: 'test vehicle_2',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now() - (1000 * 60 * (5 + Math.random() * 10)),
        remainingTime: 201500320,
        driver: undefined,
    },
    {
        name: 'test vehicle_3',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now() - (1000 * 60 * (5 + Math.random() * 10)),
        remainingTime: 201500320,
        driver: undefined,
    },
    {
        name: 'test vehicle_4',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now() - (1000 * 60 * (5 + Math.random() * 10)),
        remainingTime: 201500320,
        driver: undefined,
    },
    {
        name: 'test vehicle_5',
        speed: 0,
        status: 3,
        online: false,
        lastUpdate: Date.now() - (1000 * 60 * (5 + Math.random() * 10)),
        remainingTime: 201500320,
        driver: undefined,
    },
    {
        name: 'test vehicle_6',
        speed: 0,
        status: 3,
        online: false,
        lastUpdate: Date.now() - (1000 * 60 * (5 + Math.random() * 10)),
        remainingTime: 201500320,
        driver: undefined,
    },
];
