export default [
    {
        name: 'test vehicle',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now(),
        driver: undefined,
    },
    {
        name: 'test vehicle_1',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now(),
        driver: undefined,
    },
    {
        name: 'test vehicle_2',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now(),
        driver: undefined,
    },
    {
        name: 'test vehicle_3',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now(),
        driver: undefined,
    },
    {
        name: 'test vehicle_4',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now(),
        driver: undefined,
    },
    {
        name: 'test vehicle_5',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now(),
        driver: undefined,
    },
    {
        name: 'test vehicle_6',
        speed: 0,
        status: 3,
        online: true,
        lastUpdate: Date.now(),
        driver: undefined,
    },
];
