export default [
    {
        id: 0,
        name: 'Max Mustermann',
        speed: 0,
        status: 0,
        remainingTime: 12301000,
        online: true,
        lastUpdate: Date.now() - (1000 * 60 * 6),
        driver: undefined,
    },
    {
        id: 1,
        name: 'Peter Mustermann',
        speed: 0,
        status: 1,
        remainingTime: 12001560,
        online: true,
        lastUpdate: Date.now() - (1000 * 60 * 4),
        driver: undefined,
    },
    {
        id: 2,
        name: 'Lars Mustermann',
        speed: 0,
        status: 1,
        remainingTime: 12301500,
        online: false,
        lastUpdate: Date.now() - (1000 * 60 * 60 * 3),
        driver: undefined,
    },
    {
        id: 3,
        name: 'Hendrik Mustermann',
        speed: 0,
        status: 0,
        remainingTime: 1230560,
        online: true,
        lastUpdate: Date.now() - 1000 * 60 * 9,
        driver: undefined,
    },
];
